apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Change this line from LoadBalancer to NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
